version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  # similar-code:
  #   config:
  #     threshold: # language-specific defaults. an override will affect all languages.
  # identical-code:
  #   config:
  #     threshold: # language-specific defaults. an override will affect all languages.

plugins:
  # https://docs.codeclimate.com/docs/nodesecurity
  nodesecurity:
    enabled: true
  # https://docs.codeclimate.com/docs/stylelint
  stylelint:
    enabled: true

  # https://docs.codeclimate.com/docs/eslint
  eslint:
    enabled: true


  # https://docs.codeclimate.com/docs/fixme
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - CUSTOM

  # https://docs.codeclimate.com/docs/csslint
  csslint:
    enabled: true

  # Plugins to consider later:

  # https://docs.codeclimate.com/docs/git-legal
  # git-legal:
  #   enabled: true

  # https://docs.codeclimate.com/docs/editorconfig
  # editorconfig:
  #   enabled: true

  # https://docs.codeclimate.com/docs/grep
  # grep:
  #   enabled: true
  #     config:
  #       patterns: ...


exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/coverage"
  - "**/docs"
  - "**/*.spec.js"
