name: Deploy Dev NASA Maestro Verifier

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
    tags:
      - '*'

jobs:
  deploy-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: appdev-nasa-maestro-verifier
        run: heroku container:login

      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        run: heroku container:push web -a appdev-nasa-maestro-verifier
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        run: heroku container:release web -a appdev-nasa-maestro-verifier

    # if the push to master has tags will rebuild and push new server docker container
    deploy-docker:
      if: contains(github.ref, 'refs/tags/v')
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Publish to Registry
          uses: HurricanKai/Publish-Docker-Github-Action@master
          with:
            name: umgccaps/nasa.maestro.verifier
            username: umgccaps
            password: ${{ secrets.DOCKER_PASSWORD }}
            tagging: true
